### ISSUE TITLE
module 'torch.nn.parameter' has no attribute 'UninitializedParameter'

### ISSUE THREAD

**Issue by PaulZgy** [pyg-team/pytorch_geometric#3439]
my environment is configured as follows

![image](https://user-images.githubusercontent.com/33367765/140471127-548482fc-3804-4656-a71d-7a30ed43c7c7.png)
![image](https://user-images.githubusercontent.com/33367765/140471171-bfc45c19-e1fa-4d66-8406-dcb91e4b9e69.png)

I didn't saw the 1.5 version of torch has UninitializedParameter?

What should I do？

**Comment by rusty1s** [comment]
`UninitializedParameter` support in PyTorch was added in PyTorch 1.8.0, I believe. It should still work if you do not make any use of lazy initialization. Which code produces the error for you?

**Comment by PaulZgy** [comment]
the error is as follows:

```
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    model = Net(dataset, num_layers, hidden)
  File "/home/workspace/qin/zhangaoyang/pytorch_geometric-origin/benchmark/kernel/edge_pool.py", line 11, in __init__
    self.conv1 = GraphConv(dataset.num_features, hidden, aggr='mean')
  File "/home/workspace/qin/.conda/envs/zgytorch1.5/lib/python3.8/site-packages/torch_geometric/nn/conv/graph_conv.py", line 53, in __init__
    self.lin_rel = Linear(in_channels[0], out_channels, bias=bias)
  File "/home/workspace/qin/.conda/envs/zgytorch1.5/lib/python3.8/site-packages/torch_geometric/nn/dense/linear.py", line 52, in __init__
    self.weight = torch.nn.parameter.UninitializedParameter()
AttributeError: module 'torch.nn.parameter' has no attribute 'UninitializedParameter'
```

**Comment by rusty1s** [comment]
Can you ensure that `dataset.num_features` in `kernel/edge_pool.py` is not zero?

**Comment by PaulZgy** [comment]
it‘s zero, let me check it again, thank you very much!

**Comment by wuzeww** [comment]
> it‘s zero, let me check it again, thank you very much!

Hi

Have you solved this problem?

**Comment by wuzeww** [comment]
> Can you ensure that `dataset.num_features` in `kernel/edge_pool.py` is not zero?

Hi

I also have the above error, the error is as follows:

![2022-01-03 16-38-00屏幕截图](https://user-images.githubusercontent.com/44798683/147915016-0933c455-059d-47ab-936d-7cc3e2afe9c4.png)

the torch version is 1.7.0

**Comment by PaulZgy** [comment]
> 

ensure that dataset.num_features is not zero, and toch1.7 has no attribute "UninitializedParameter". you may to update torch to >= 1.8

**Comment by nickiser** [comment]
I have the same problem, number of features is not zero, version is 1.7.1. Please help!
![image](https://user-images.githubusercontent.com/94193999/152589431-0cfc3d30-75c3-43db-accd-7dc9916d8c97.png)

**Comment by nickiser** [comment]
![image](https://user-images.githubusercontent.com/94193999/152590897-708e2a01-8457-40c5-aec1-92fff0591e63.png)

**Comment by rusty1s** [comment]
Thanks for reporting. Can you install from master and try again?
```
pip install git+https://github.com/pyg-team/pytorch_geometric.git
```
I'm pretty sure I fixed that in https://github.com/pyg-team/pytorch_geometric/commit/973d17d888b6b3139dd516baa31d9f3ccac2898a.

**Comment by LindaSt** [comment]
I have the same problem with PyTorch 1.7.1, torch-cluster 1.5.8, torch-geometric 2.0.3, torch-scatter 2.0.5, torch-sparse 0.6.9. Just installed the environment today.

**Comment by rusty1s** [comment]
Yes, you will need to install PyG from master version 2.04) as mentioned above.

**Comment by LindaSt** [comment]
@rusty1s I've done that but I still get this error for GraphSAGE and GCNConv.

**Comment by rusty1s** [comment]
Can you link the error or is it the same?

**Comment by LindaSt** [comment]
My bad, I've tried again this morning and it works now. Maybe my PyCharm was being a bit weird. Thanks anyways :)

**Comment by LindaSt** [comment]
I get the same error as above `AttributeError: module 'torch.nn.parameter' has no attribute 'UninitializedParameter'` after the first epoch finishes.

**Comment by LindaSt** [comment]
Sure, this is the traceback for GraphSAGE:
```
Epoch 0: 100%|█████████| 158/158 [00:13<00:00, 11.55it/s, loss=4.61, v_num=duz8]Traceback (most recent call last):
  File "/HOME/studerl/GraphNeuralNetworkExperiments/project/dualgraph_experiments_sythetic_handwriting.py", line 60, in <module>
    DualGraphSynthetic(**kwargs).main()
  File "/HOME/studerl/GraphNeuralNetworkExperiments/project/experiment_template.py", line 174, in main
    self.one_run()
  File "/HOME/studerl/GraphNeuralNetworkExperiments/project/experiment_template.py", line 157, in one_run
    trainer.fit(model=model, train_dataloaders=train_loader, val_dataloaders=val_loader)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 151, in run
    output = self.on_run_end()
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 298, in on_run_end
    self.trainer.call_hook("on_train_epoch_end")
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1495, in call_hook
    callback_fx(*args, **kwargs)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 93, in on_train_epoch_end
    callback.on_train_epoch_end(self, self.lightning_module)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 321, in on_train_epoch_end
    self.save_checkpoint(trainer)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 396, in save_checkpoint
    self._save_top_k_checkpoint(trainer, monitor_candidates)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 683, in _save_top_k_checkpoint
    self._update_best_and_save(current, trainer, monitor_candidates)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 740, in _update_best_and_save
    trainer.save_checkpoint(filepath, self.save_weights_only)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1913, in save_checkpoint
    self.checkpoint_connector.save_checkpoint(filepath, weights_only)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 477, in save_checkpoint
    _checkpoint = self.dump_checkpoint(weights_only)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 379, in dump_checkpoint
    "state_dict": self._get_lightning_module_state_dict(),
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 491, in _get_lightning_module_state_dict
    state_dict = self.trainer.training_type_plugin.lightning_module_state_dict()
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 284, in lightning_module_state_dict
    return model.state_dict()
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch/nn/modules/module.py", line 907, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch/nn/modules/module.py", line 907, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch/nn/modules/module.py", line 907, in state_dict
    module.state_dict(destination, prefix + name + '.', keep_vars=keep_vars)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch/nn/modules/module.py", line 904, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/HOME/studerl/.conda/envs/gnn-updated/lib/python3.8/site-packages/torch_geometric/nn/dense/linear.py", line 124, in _save_to_state_dict
    if isinstance(self.weight, nn.parameter.UninitializedParameter):
AttributeError: module 'torch.nn.parameter' has no attribute 'UninitializedParameter'
```
And this is the traceback for GCN:
```
```

Here also my package versions:
<img width="251" alt="grafik" src="https://user-images.githubusercontent.com/17549983/154059198-c638ae17-7905-4ede-98a6-9dc4524e1c80.png">

**Comment by rusty1s** [comment]
Thank you! This is indeed a different issue. I think I fixed it in https://github.com/pyg-team/pytorch_geometric/pull/4086.

**Comment by Alrodr** [comment]
Hello everyone
 I get the same error `AttributeError: module 'torch.nn.parameter' has no attribute 'UninitializedParameter'`
 Traceback:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [5], in <module>
     32 device = torch.device('cpu')
     33 # device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
---> 34 model = Net(dataset.num_features, 2).to(device)
     35 data = data.to(device)
     36 optimizer = torch.optim.Adam(model.parameters(), lr=0.005, weight_decay=5e-4)

Input In [5], in Net.__init__(self, in_channels, out_channels)
     16 def __init__(self, in_channels, out_channels):
     17     super().__init__()
---> 19     self.conv1 = GATConv(in_channels, 8, heads=8, dropout=0.6)
     20     # On the Pubmed dataset, use heads=8 in conv2.
     21     self.conv2 = GATConv(8 * 8, out_channels, heads=1, concat=False,
     22                          dropout=0.6)

File ~/ai-gnn/env/lib/python3.8/site-packages/torch_geometric/nn/conv/gat_conv.py:133, in GATConv.__init__(self, in_channels, out_channels, heads, concat, negative_slope, dropout, add_self_loops, edge_dim, fill_value, bias, **kwargs)
    130 # In case we are operating in bipartite graphs, we apply separate
    131 # transformations 'lin_src' and 'lin_dst' to source and target nodes:
    132 if isinstance(in_channels, int):
--> 133     self.lin_src = Linear(in_channels, heads * out_channels,
    134                           bias=False, weight_initializer='glorot')
    135     self.lin_dst = self.lin_src
    136 else:

File ~/ai-gnn/env/lib/python3.8/site-packages/torch_geometric/nn/dense/linear.py:61, in Linear.__init__(self, in_channels, out_channels, bias, weight_initializer, bias_initializer)
     59     self.weight = Parameter(torch.Tensor(out_channels, in_channels))
     60 else:
---> 61     self.weight = nn.parameter.UninitializedParameter()
     62     self._hook = self.register_forward_pre_hook(
     63         self.initialize_parameters)
     65 if bias:

AttributeError: module 'torch.nn.parameter' has no attribute 'UninitializedParameter'`

Thank you!

**Comment by rusty1s** [comment]
This should only happen in case `in_channels` is less than zero. Can you check?

**Comment by ymoghadd** [comment]
I have also been running into this issue and in_channels is not less than zero. This is the traceback:

  File "/home/ymoghadd/GNN4TJ/rtl2vec/core/trainer.py", line 111, in build
    self.model = GCN(self.num_feature_dim, self.config.hidden, 2, self.config.dropout, self.config.pooling_type, self.config.readout_type).to(self.config.device)
  File "/home/ymoghadd/GNN4TJ/rtl2vec/core/gcn.py", line 16, in __init__
    self.gc1 = GCNConv(nfeat, nhid)
  File "/home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.6/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 140, in __init__
    weight_initializer='glorot')
  File "/home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.6/site-packages/torch_geometric/nn/dense/linear.py", line 67, in __init__
    self.reset_parameters()
  File "/home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.6/site-packages/torch_geometric/nn/dense/linear.py", line 80, in reset_parameters
    if isinstance(self.weight, nn.parameter.UninitializedParameter):
AttributeError: module 'torch.nn.parameter' has no attribute 'UninitializedParameter'

**Comment by rusty1s** [comment]
It looks like you are not running PyG on master, aren‘t you? You can install via
```
pip install git+https://github.com/pyg-team/pytorch_geometric.git
```
To confirm, `torch_geometric.__version__` should output `2.0.4`.

**Comment by ymoghadd** [comment]
Thank you for your swift response. I uninstalled the version of python I had, which was 3.6, and installed version 3.7, since running PyG on master requires a version >= 3.7. I then had to install torch scatter, but when I run the following command: pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html (the code I'm running requires PyTorch version 1.7 and  cuda version 10.2) but I get the following error: 

Building wheel for torch-scatter (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ymoghadd/anaconda3/envs/GNN4TJ_3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j6jgav5x/torch-scatter_7e8c8281395
a43e298e58db43049d9f6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j6jgav5x/torch-scatter_7e8c8281395a43e298e58db43049d9f6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)
(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile
(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-e53c4v5o
       cwd: /tmp/pip-install-j6jgav5x/torch-scatter_7e8c8281395a43e298e58db43049d9f6/
  Complete output (45 lines):
  /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future 
versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/torch_scatter
  copying torch_scatter/scatter.py -> build/lib.linux-x86_64-3.8/torch_scatter
  copying torch_scatter/placeholder.py -> build/lib.linux-x86_64-3.8/torch_scatter
  copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-3.8/torch_scatter
  copying torch_scatter/utils.py -> build/lib.linux-x86_64-3.8/torch_scatter
  copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-3.8/torch_scatter
  copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.8/torch_scatter
  creating build/lib.linux-x86_64-3.8/torch_scatter/composite
  copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-3.8/torch_scatter/composite
  copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-3.8/torch_scatter/composite
  copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-3.8/torch_scatter/composite
  copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-3.8/torch_scatter/composite
  running build_ext
building 'torch_scatter._scatter_cpu' extension                                                                                                                          [174/1616]
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/csrc
  creating build/temp.linux-x86_64-3.8/csrc/cpu
  gcc -pthread -B /home/ymoghadd/anaconda3/envs/GNN4TJ_3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc -I/home/ymogha
dd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include -I/home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/hom
e/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/TH -I/home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/THC -I/home/ymogha
dd/anaconda3/envs/GNN4TJ_3/include/python3.8 -c csrc/scatter.cpp -o build/temp.linux-x86_64-3.8/csrc/scatter.o -O2 -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPY
BIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  csrc/scatter.cpp: In static member function ‘static torch::autograd::variable_list ScatterMean::forward(torch::autograd::AutogradContext*, torch::autograd::Variable, torch::autogr
ad::Variable, int64_t, c10::optional<at::Tensor>, c10::optional<long int>)’:
  csrc/scatter.cpp:135:30: error: no matching function for call to ‘at::Tensor::div_(at::Tensor&, const char [6])’
         out.div_(count, "floor");
                                ^
  In file included from /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3:0,
                   from /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                   from /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                   from /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                   from /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/torch/script.h:3,
                   from csrc/scatter.cpp:2:
  /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:676:12: note: candidate: at::Tensor& at::Tensor::div_(const at::Tensor&) co
nst
     Tensor & div_(const Tensor & other) const;
              ^~~~
  /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:676:12: note:   candidate expects 1 argument, 2 provided
  /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:678:12: note: candidate: at::Tensor& at::Tensor::div_(c10::Scalar) const
     Tensor & div_(Scalar other) const;
              ^~~~
  /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:678:12: note:   candidate expects 1 argument, 2 provided
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter                                                                                                                                 [141/1616]
Failed to build torch-scatter
Installing collected packages: torch-scatter
    Running setup.py install for torch-scatter ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ymoghadd/anaconda3/envs/GNN4TJ_3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j6jgav5x/torch-scatter_7e8c82813
95a43e298e58db43049d9f6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j6jgav5x/torch-scatter_7e8c8281395a43e298e58db43049d9f6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', ope
n)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compi
le(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ma_pscac/install-record.txt --single-version-externally-managed --compile --install-headers /home/ymoghadd/anac
onda3/envs/GNN4TJ_3/include/python3.8/torch-scatter
         cwd: /tmp/pip-install-j6jgav5x/torch-scatter_7e8c8281395a43e298e58db43049d9f6/
    Complete output (45 lines):
    /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in futur
e versions. Please use the underscore name 'description_file' instead
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/torch_scatter
    copying torch_scatter/scatter.py -> build/lib.linux-x86_64-3.8/torch_scatter
    copying torch_scatter/placeholder.py -> build/lib.linux-x86_64-3.8/torch_scatter
    copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-3.8/torch_scatter
    copying torch_scatter/utils.py -> build/lib.linux-x86_64-3.8/torch_scatter
    copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-3.8/torch_scatter
    copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.8/torch_scatter
    creating build/lib.linux-x86_64-3.8/torch_scatter/composite
    copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-3.8/torch_scatter/composite
    copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-3.8/torch_scatter/composite
    copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-3.8/torch_scatter/composite
    copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-3.8/torch_scatter/composite
    running build_ext
    building 'torch_scatter._scatter_cpu' extension                                                                                                                        [108/1616]
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/csrc
    creating build/temp.linux-x86_64-3.8/csrc/cpu
    gcc -pthread -B /home/ymoghadd/anaconda3/envs/GNN4TJ_3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Icsrc -I/home/ymog
hadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include -I/home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/h
ome/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/TH -I/home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/THC -I/home/ymog
hadd/anaconda3/envs/GNN4TJ_3/include/python3.8 -c csrc/scatter.cpp -o build/temp.linux-x86_64-3.8/csrc/scatter.o -O2 -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -D
PYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    csrc/scatter.cpp: In static member function ‘static torch::autograd::variable_list ScatterMean::forward(torch::autograd::AutogradContext*, torch::autograd::Variable, torch::auto
grad::Variable, int64_t, c10::optional<at::Tensor>, c10::optional<long int>)’:
    csrc/scatter.cpp:135:30: error: no matching function for call to ‘at::Tensor::div_(at::Tensor&, const char [6])’
           out.div_(count, "floor");
                                  ^
    In file included from /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3:0,
                     from /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                     from /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                     from /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/torch/script.h:3,
                     from csrc/scatter.cpp:2:
    /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:676:12: note: candidate: at::Tensor& at::Tensor::div_(const at::Tensor&) 
const
       Tensor & div_(const Tensor & other) const;
                ^~~~
    /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:676:12: note:   candidate expects 1 argument, 2 provided
    /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:678:12: note: candidate: at::Tensor& at::Tensor::div_(c10::Scalar) const
       Tensor & div_(Scalar other) const;
                ^~~~
    /home/ymoghadd/anaconda3/envs/GNN4TJ_3/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:678:12: note:   candidate expects 1 argument, 2 provided
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ymoghadd/anaconda3/envs/GNN4TJ_3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install
-j6jgav5x/torch-scatter_7e8c8281395a43e298e58db43049d9f6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j6jgav5x/torch-scatter_7e8c8281395a43e298e58db43049d9f6/setup.py'"'"';f = geta
ttr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '
"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ma_pscac/install-record.txt --single-version-externally-managed --compile --in
stall-headers /home/ymoghadd/anaconda3/envs/GNN4TJ_3/include/python3.8/torch-scatter Check the logs for full command output.

**Comment by rusty1s** [comment]
Since this is an older release, you have to specify the latest supported `torch-scatter` version, see [here](https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html) (which holds for the other packages as well):
```
pip install torch-scatter==2.0.7 -f https://pytorch-geometric.com/whl/torch-1.7.0+cu102.html
```

**Comment by ymoghadd** [comment]
Is there a solution to the module 'torch.nn.parameter' has no attribute 'UninitializedParameter' without having to run PyG on master? Because the installation requires python >= 3.7 and my python version is 3.6.

**Comment by rusty1s** [comment]
The only option is to go back to an earlier version, *e.g.*, `torch-geometric==1.7.2`. We will drop Python 3.6 support in the next release.
