### ISSUE TITLE
Crash on Google Colab when importing torch_geometric

### ISSUE THREAD

**Issue by zhuozuoy** [pyg-team/pytorch_geometric#4539]
### 🐛 Describe the bug

I follow the instruction in Notebook: Tutorial12 GAE for link prediction.ipynb on https://pytorch-geometric.readthedocs.io/en/latest/notes/colabs.html

I install the PyG on Google Colab using the code inside:
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

When I run either code
import torch_geometric
from torch_geometric.data import Data
The colab notebook will crash and restart.

### Environment

* PyG version: 2.0.5
* PyTorch version: 1.10.2
* OS: Google Colab
* Python version: 3.7
* CUDA/cuDNN version: 113
* How you installed PyTorch and PyG (`conda`, `pip`, source): 
* !pip install -q torch-scatter -f https://data.pyg.org/whl/torch-1.10.2+cu113.html
   !pip install -q torch-sparse -f https://data.pyg.org/whl/torch-1.10.2+cu113.html
   !pip install -q git+https://github.com/pyg-team/pytorch_geometric.git
* Any other relevant information (*e.g.*, version of `torch-scatter`):torch-scatter: 2.0.9      torch-sparse: 0.6.13

**Comment by rusty1s** [comment]
Colab just upgraded to PyTorch 1.11, so running
```
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-1.11.0+cu113.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-1.11.0+cu113.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git
```
should fix this.

@AntonioLonga Any chance we can fix this for your Google Colabs as well? We can also integrate a PyTorch version agnostic approach, e.g., via
```
import os
import torch
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git
```

**Comment by zhuozuoy** [comment]
Thanks a lot.
That fix the issue.

**Comment by AntonioLonga** [comment]
@rusty1s 
Sure! 
I'll try to fix the bug with the agnostic approach really soon. 


Thanks

**Comment by pleonova** [comment]
Running into the same issue, but unfortunately the above code snippets did not solve my issue and my kernel keeps crashing with the following error log message. Weirdly enough, it was working just fine yesterday. My kernel crashes and restarts every time I try to run:
`import torch_geometric.transforms as T`

Timestamp | Level | Message
May 25, 2022, 10:39:01 AM | WARNING | WARNING:root:kernel b9abb555-8a42-4ec5-9a12-406934a070ae restarted
May 25, 2022, 10:39:01 AM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports


I even tried to follow the OP's tutorial, but had the same problem (https://colab.research.google.com/github/AntonioLonga/PytorchGeometricTutorial/blob/main/Tutorial12/Tutorial12%20GAE%20for%20link%20prediction.ipynb#scrollTo=fqc4E_ZzR3QR) from PyG and updating the first pip installation to: 
```
import os
import torch
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

```
Output:
**1.11.0+cu113**



**Environment**
PyG version: 2.0.5
PyTorch version: 1.11.0
OS: Google Colab (and I am Pro subscriber)
Python version: 3.7.13
CUDA/cuDNN version: 11.1


UPDATE:
Just came across this post from 2020: https://github.com/pyg-team/pytorch_geometric/issues/1876
Running the following before the three `!pip` above seemed to solve the issue
`!pip install pip==20.2.4`

**Comment by arisioz** [comment]
I would suggest to run `torch.__version__` and fixing the link for pyg accordingly. At the time of writing the version of torch would be `1.13.1+cu116`. I would need to pass `https://data.pyg.org/whl/torch-1.13.1+cu116.html` as a link to be parsed by pip.
