### ISSUE TITLE
MessagePassing: propagate method

### ISSUE THREAD

**Issue by Angelo92Git** [pyg-team/pytorch_geometric#9059]
### 📚 Describe the documentation issue

The example code in the docs linked below appears to error when calling the propagate method (torch_geometric version 2.5.1)
https://pytorch-geometric.readthedocs.io/en/latest/tutorial/create_gnn.html

Specifically the line calling "propagate" in the forward method of the GCNConv class.
```
out = self.propagate(edge_index, x=x, norm=norm)
```

When applied to a simple graph as an input, the following error is triggered:
```
TypeError: propagate() got an unexpected keyword argument 'x'
```

Documentation of propagate method suggests that it can accept keyword arguments so it is unclear why this error is triggered.

**Comment by sreebhattacharyya** [comment]
Facing the same issue. Would be helpful to have a clarification!

**Comment by jiamubai** [comment]
> Facing the same issue. Would be helpful to have a clarification!

Facing the same issue with 2.5.1. Just tried the version of 2.4.0 and it works.

**Comment by rusty1s** [comment]
Do you mind sharing some information about your system? OS? Are you running this in Google Colab, etc?

**Comment by Angelo92Git** [comment]
I got the error on both my PC (on WSL (Windows Subsystem for Linux)) as well as Google Colab.

Here's a link to a Colab notebook that reproduces the error:
https://colab.research.google.com/drive/1ARW6IWmKcaOqsC_tORpk5NySFSwjw1UV?usp=sharing

**Comment by rusty1s** [comment]
Thanks. This is indeed a pretty critical bug, which I will resolve in https://github.com/pyg-team/pytorch_geometric/pull/9068 (we don't correctly raise an exception here). After it is merged, you can either install PyG from master/nightly or wait till I cut 2.5.2. Really sorry :(

**Comment by mishooax** [comment]
@rusty1s I am getting this error with pyg 2.5.3 😢 

```
  File "layers/conv.py", line 97, in forward
    out = self.propagate(
TypeError: propagate() got an unexpected keyword argument 'heads'
```

calling function:

```python3
class CustomMP(MessagePassing):
      def forward(
         self, ...
      ):
        heads = ...
        out = self.propagate(
            heads=heads, edge_index=edge_index, ...
        )
```

any suggestions?

**Comment by mishooax** [comment]
A colleague suggested I pass `heads` as the _2nd_ keyword argument:
```python3
out = self.propagate(edge_index=edge_index, heads=heads, ... )
```
and this appears to work. It's surprising, though - I'd have expected the order of the keyword arguments being passed in not to matter, e.g.
```shell
$ python3
Python 3.10.10 on linux
>>> def f(a, b=1, c="test"):
...   return a + b
... 
>>> f(b=10,a=20)
30
>>> f(a=20,b=10)
30
```

**Comment by rusty1s** [comment]
That's indeed a current limitation of our implementation. Let me take a look :)

**Comment by xingxindrst** [comment]
> Will be fixed in #9245.

Hello,I had met the same error running propagate method.TypeError: propagate() got an unexpected keyword argument 'x'。
![1714291900248](https://github.com/pyg-team/pytorch_geometric/assets/84786188/083bf0f2-98f2-4777-bf64-4ac20aaf1b30)
However, when I swap the position of the parameters，I had met another error.
![1714294152416](https://github.com/pyg-team/pytorch_geometric/assets/84786188/f4d9a80b-9383-47fc-a89f-b6ed236c9f9a)
The error location is this method.
Can you please help me look at this issue?Thanks.

**Comment by xingxindrst** [comment]
> > Will be fixed in #9245.
> 
> Hello,I had met the same error running propagate method.TypeError: propagate() got an unexpected keyword argument 'x'。 ![1714291900248](https://private-user-images.githubusercontent.com/84786188/326242752-083bf0f2-98f2-4777-bf64-4ac20aaf1b30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTU5NjQsIm5iZiI6MTcxNDM1NTY2NCwicGF0aCI6Ii84NDc4NjE4OC8zMjYyNDI3NTItMDgzYmYwZjItOThmMi00Nzc3LWJmNjQtNGFjMjBhYWYxYjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAxNTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOTM3OGFlNzkzMmFmMmZlMDBiYTRiNzY4NjdlMjQ0YWYxMTI2MmU0NjFjN2EzZTQyZjczYzcyZjc5ZjdkMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FdcjOKxOt_GAbLUqC2Ig72juvglqA5RFQ37_8fdLWcQ) However, when I swap the position of the parameters，I had met another error. ![1714294152416](https://private-user-images.githubusercontent.com/84786188/326242964-f4d9a80b-9383-47fc-a89f-b6ed236c9f9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTU5NjQsIm5iZiI6MTcxNDM1NTY2NCwicGF0aCI6Ii84NDc4NjE4OC8zMjYyNDI5NjQtZjRkOWE4MGItOTM4My00N2ZjLWE4OWYtYjZlZDIzNmM5ZjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAxNTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZGQ1MzA0ZmNlODg0ZjgwYTM2OWJhN2M3OTZmZDZlOTk1YzdmOWQ3ZDBjNzdlZTA0OGZkZDZhM2E5NDdmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XZY0qoTw5za1gphIOGY4tqEIObbQ9BfAy9lF-uiyR90) The error location is this method. Can you please help me look at this issue?Thanks.

I have solved this problem.It's my pytorch version that's too high。

**Comment by cszhangzhen** [comment]
Hi,

I installed PyG from master (version 2.6.0), but I still have this error `TypeError: propagate() got an unexpected keyword argument...`.

The version 2.4.0 works and the version 2.5.3 does not work.

#9245 has been merged into the master branch, but it seems that the problem still exists.

**Comment by rusty1s** [comment]
This has been only fixed on master AFAIK.

**Comment by carmen-martin** [comment]
Hello, 

The issue still persists for me with both v2.5.3 and v2.6 (installed from master). I get the error `TypeError: propagate() got an unexpected keyword argument 'edge_attr'`, when calling `out = self.propagate(edge_index, size=size, x=x, edge_attr=edge_attr)`.

I'm using python 3.11.5 on a linux machine, with pytorch 2.1.2.

Do you have any idea on what the issue can be? And any suggestions on how to fix it?

Thanks a lot in advance!

**Comment by aqlkzf** [comment]
Hi,    TypeError: propagate() got an unexpected keyword argument 'gpedge_weight'   I still met the bug, I just use  pip install git+https://github.com/pyg-team/pytorch_geometric.git   to intall 
`Collecting git+https://github.com/pyg-team/pytorch_geometric.git
  Cloning https://github.com/pyg-team/pytorch_geometric.git to /tmp/pip-req-build-efs1xa6c
  Running command git clone --filter=blob:none --quiet https://github.com/pyg-team/pytorch_geometric.git /tmp/pip-req-build-efs1xa6c
  Resolved https://github.com/pyg-team/pytorch_geometric.git to commit fbafbc4fc9181e8759ec1f39d9618992793b5fe1
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: aiohttp in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from torch-geometric==2.6.0) (3.9.5)
Requirement already satisfied: fsspec in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from torch-geometric==2.6.0) (2024.6.1)
Requirement already satisfied: jinja2 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from torch-geometric==2.6.0) (3.1.4)
Requirement already satisfied: numpy in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from torch-geometric==2.6.0) (1.26.4)
Requirement already satisfied: psutil>=5.8.0 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from torch-geometric==2.6.0) (6.0.0)
Requirement already satisfied: pyparsing in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from torch-geometric==2.6.0) (3.1.2)
Requirement already satisfied: requests in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from torch-geometric==2.6.0) (2.32.3)
Requirement already satisfied: tqdm in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from torch-geometric==2.6.0) (4.66.4)
Requirement already satisfied: aiosignal>=1.1.2 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from aiohttp->torch-geometric==2.6.0) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from aiohttp->torch-geometric==2.6.0) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from aiohttp->torch-geometric==2.6.0) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from aiohttp->torch-geometric==2.6.0) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from aiohttp->torch-geometric==2.6.0) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from aiohttp->torch-geometric==2.6.0) (4.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from jinja2->torch-geometric==2.6.0) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from requests->torch-geometric==2.6.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from requests->torch-geometric==2.6.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from requests->torch-geometric==2.6.0) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /ss03/ssd/s1155202250/basic/conda/envs/pyGtest/lib/python3.10/site-packages (from requests->torch-geometric==2.6.0) (2024.7.4)`  
Thanks for your attention.

**Comment by MultiMeowMeow** [comment]
It seems the bug still exists on master/nightly? My code won't report this error on version 2.3.1, but doesn't work on 2.6.0

**Comment by ldv1** [comment]
I have the same problem with 2.6.1. It works though with 2.4.0.

**Comment by Deno-V** [comment]
I face this same problem, but i am passing edge_attr to self.propagate... 2.6.1
