### ISSUE TITLE
Loading Cora/PubMed dataset is unsuccessful

### ISSUE THREAD

**Issue by YaoXinZhi** [pyg-team/pytorch_geometric#988]
## 🐛 Bug

This bug occurred when i tried to load Cora dataset.

`
from torch_geometric.datasets import Planetoid
dataset = Planetoid(root='Cora', name='Cora')
`

`
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
`

I noticed that I thought the download URL was wrong, so I changed planetoid.py

`
    url = 'https://github.com/kimiyoung/planetoid/raw/master/data'
    #url = 'https://github.com/kimiyoung/planetoid/tree/master/data'

`

But a new bug happened.

`Processing...
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 34, in __init__
  File "/home/xinzhi/PycharmProjects/PyG_project/venv/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/home/xinzhi/PycharmProjects/PyG_project/venv/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/home/xinzhi/PycharmProjects/PyG_project/venv/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "<input>", line 59, in process
  File "/home/xinzhi/PycharmProjects/PyG_project/venv/lib/python3.6/site-packages/torch_geometric/io/planetoid.py", line 19, in read_planetoid_data
    items = [read_file(folder, prefix, name) for name in names]
  File "/home/xinzhi/PycharmProjects/PyG_project/venv/lib/python3.6/site-packages/torch_geometric/io/planetoid.py", line 19, in <listcomp>
    items = [read_file(folder, prefix, name) for name in names]
  File "/home/xinzhi/PycharmProjects/PyG_project/venv/lib/python3.6/site-packages/torch_geometric/io/planetoid.py", line 67, in read_file
    else:
_pickle.UnpicklingError: invalid load key, '\x0a'.
`

**Comment by jinxinbao** [comment]
I have the same problem,but when i open the  link in the firefox, i can download the dataset.
and i want to know where i put the dataset.

**Comment by YaoXinZhi** [comment]
When you call the data set you define the path, you just put it under the path you defined. But I wonder if you changed the url when you downloaded it

**Comment by rusty1s** [comment]
Can you try to pass in an absolute path? If this still does not work, put all files under `Cora/raw`

**Comment by jinxinbao** [comment]
> When you call the data set you define the path, you just put it under the path you defined. But I wonder if you changed the url when you downloaded it

**Comment by jinxinbao** [comment]
> When you call the data set you define the path, you just put it under the path you defined. But I wonder if you changed the url when you downloaded it

**Comment by jinxinbao** [comment]
I do not change the url ,just url = 'https://github.com/kimiyoung/planetoid/raw/master/data'

**Comment by jinxinbao** [comment]
I fixed it after putting all files under Cora/raw.  Very thank you !

**Comment by YaoXinZhi** [comment]
I solved the problem by downloading the file directly, thank you very much!

**Comment by kangkang59812** [comment]
> I fixed it after putting all files under Cora/raw. Very thank you !

Where is the absolute path？（？？？/Cora/raw）thanks！

**Comment by xuexiaoxiaohu** [comment]
/home/lr/download/pytorch_geometric-master/data/Core/raw

**Comment by YaoXinZhi** [comment]
If you want to use an absolute path, you need to adjust your code, and the absolute path for each person to download the file is different. . . You can search for the concept of absolute path in Baidu or Google

**Comment by jiaruHithub** [comment]
> 调用数据集时，您定义路径，只是将其放在定义的路径下。但我想知道您下载时是否更改了网址

How to download directly?

**Comment by jiaruHithub** [comment]
> I solved the problem by downloading the file directly, thank you very much!

How to download directly? I have same problem too

**Comment by xuexiaoxiaohu** [comment]
> > I solved the problem by downloading the file directly, thank you very much!
> 
> How to download directly? I have same problem too

 'https://github.com/kimiyoung/planetoid/raw/master/data'

**Comment by rusty1s** [comment]
Yes, download the all the files from [https://github.com/kimiyoung/planetoid/raw/master/data](here), and put them inside the `raw` folder in the path that you specified for the `Planetoid` dataset.

**Comment by jiaruHithub** [comment]
> > > I solved the problem by downloading the file directly, thank you very much!
> > 
> > 
> > How to download directly? I have same problem too
> 
> 'https://github.com/kimiyoung/planetoid/raw/master/data'

Thank you.I have been solved this problem!

**Comment by jiaruHithub** [comment]
> Yes, download the all the files from [https://github.com/kimiyoung/planetoid/raw/master/data](here), and put them inside the `raw` folder in the path that you specified for the `Planetoid` dataset.

Thank you.I have been solved this problem!!

**Comment by KrabbeJing** [comment]
![image](https://user-images.githubusercontent.com/43301545/83017045-8a3ae000-a055-11ea-9d1d-40f6d580fcb4.png)
dataset = Planetoid(root='data/planetoid', name='Cora')
this is my hierarchical structure

**Comment by huangJC0429** [comment]
I meet same problem, Just download Cora datasets by browser, and copy it to the ../data/raw floder

**Comment by sin3000x** [comment]
For any one still encounters `_pickle.UnpicklingError: invalid load key, '\x0a'.` after putting the files in that folder: download by hitting the github "Download raw file" button, not by right clicking and "Save the link as..."
